
pipeline 
{
    agent any

    stages 
    {
        stage('Build') 
        {
            steps 
            {
                echo 'Build Application'
            }
        }
        
    
            stage('Test') 
         {   
    
            steps 
            
           {
                echo 'Test Application'
            }
			
		}
            stage('Hello') 
            
        {
            steps 
            
            {
                echo 'deploy'
            }
        
        }
        
     }   
     post
     {
    
          always
          {
             emailext body: 'Summary ', subject: 'Pipeline status', to: 'jenkins10101995@gmail.com' 
          }
     }
        
        
 }
